# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-19 20:03
from __future__ import unicode_literals

from django.db import migrations
import instacode.util


class Migration(migrations.Migration):

    dependencies = [
        ('instacode', '0002_auto_20160919_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='params',
            field=instacode.util.JSONField(blank=True, default=None, null=True, verbose_name=b'Parameters'),
        ),
    ]
