# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-19 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instacode', '0003_auto_20160919_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='temp_owner',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Temporary owner session ID'),
        ),
    ]
