# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-23 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instacode', '0004_photo_temp_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
