# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-23 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instacode', '0005_photo_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='temp_owner',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name=b'Temporary owner session ID'),
        ),
    ]
